apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pk7k2sugg-go
  janus-idp.io/tekton: pk7k2sugg-go
  backstage.io/kubernetes-id: pk7k2sugg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pk7k2sugg-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
