apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pk7k2sugg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pk7k2sugg-go 
  name: pk7k2sugg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pk7k2sugg-go 
